spring.application.name=parking-control

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/parking-control-db
spring.datasource.username=postgres
spring.datasource.password=18042279
spring.jpa.show-sql= true

spring.docker.compose.enabled=false

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
